/* Generated By:JJTree: Do not edit this line. ASTAdditiveOperator.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTAdditiveOperator extends SimpleNode {
  public ASTAdditiveOperator(int id) {
    super(id);
  }

  public ASTAdditiveOperator(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=02eacce24ad4f238e9a0e610f2daf4a9 (do not edit this line) */
