/* Generated By:JJTree: Do not edit this line. ASTAdditiveExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTAdditiveExp extends SimpleNode {
  public ASTAdditiveExp(int id) {
    super(id);
  }

  public ASTAdditiveExp(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1407ee30d3e5a2ff59bfffcbf421c5e4 (do not edit this line) */
