/* Generated By:JJTree: Do not edit this line. ASTClassDeclSimple.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTClassDeclSimple extends SimpleNode {
  public ASTClassDeclSimple(int id) {
    super(id);
  }

  public ASTClassDeclSimple(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b93e209f0099235aaf6b4d9f1cd51ea2 (do not edit this line) */
