/* Generated By:JJTree: Do not edit this line. ASTDotLengthExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTDotLengthExp extends SimpleNode {
  public ASTDotLengthExp(int id) {
    super(id);
  }

  public ASTDotLengthExp(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=85b96507a6c845687157d1b15f42dd6f (do not edit this line) */
