/* Generated By:JJTree: Do not edit this line. ASTIntegerConstNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTIntegerConstNode extends SimpleNode {
  public ASTIntegerConstNode(int id) {
    super(id);
  }

  public ASTIntegerConstNode(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b03ca2a8f8e4aa90f00c4827fb819a6e (do not edit this line) */
