/* Generated By:JJTree: Do not edit this line. ASTLengthExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTLengthExp extends SimpleNode {
  public ASTLengthExp(int id) {
    super(id);
  }

  public ASTLengthExp(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1296cf7dd0fa8df0671bf55f070dbfde (do not edit this line) */
