/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMultiplicativeExp extends SimpleNode {
  public ASTMultiplicativeExp(int id) {
    super(id);
  }

  public ASTMultiplicativeExp(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c284f56d56851697fe330f82cc94c34c (do not edit this line) */
