/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeOperator.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTMultiplicativeOperator extends SimpleNode {
  public ASTMultiplicativeOperator(int id) {
    super(id);
  }

  public ASTMultiplicativeOperator(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e9dd6fe399df48faeec76e5a03ae67d2 (do not edit this line) */
