/* Generated By:JJTree: Do not edit this line. ASTNewIntArrayNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTNewIntArrayNode extends SimpleNode {
  public ASTNewIntArrayNode(int id) {
    super(id);
  }

  public ASTNewIntArrayNode(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9936856765d338e1e39ca6a4497a21d4 (do not edit this line) */
