/* Generated By:JJTree: Do not edit this line. ASTRelationalOperator.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTRelationalOperator extends SimpleNode {
  public ASTRelationalOperator(int id) {
    super(id);
  }

  public ASTRelationalOperator(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bb16f5f0cef295bed92b44cc271f3cbe (do not edit this line) */
