/* Generated By:JJTree: Do not edit this line. ASTRelationalExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTRelationalExp extends SimpleNode {
  public ASTRelationalExp(int id) {
    super(id);
  }

  public ASTRelationalExp(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a1ffd8d52bca99c430c1d623c0df1a43 (do not edit this line) */
