/* Generated By:JJTree: Do not edit this line. ASTVarDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=TNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class ASTVarDecl extends SimpleNode {
  public ASTVarDecl(int id) {
    super(id);
  }

  public ASTVarDecl(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=45e5f6cc62378fb3cdb404eb5e43c3ad (do not edit this line) */
