/* Generated By:JavaCC: Do not edit this line. MiniJavaParserTreeConstants.java Version 7.0.9 */
package AST;

public interface MiniJavaParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAINCLASS = 1;
  public int JJTVOID = 2;
  public int JJTCLASSDECLSIMPLE = 3;
  public int JJTCLASSDECLEXTENDS = 4;
  public int JJTVARDECL = 5;
  public int JJTMETHODDECL = 6;
  public int JJTRETURNSTM = 7;
  public int JJTFORMALLIST = 8;
  public int JJTFORMALREST = 9;
  public int JJTTYPE = 10;
  public int JJTBLOCK = 11;
  public int JJTIF = 12;
  public int JJTWHILE = 13;
  public int JJTPRINT = 14;
  public int JJTASSIGN = 15;
  public int JJTARRAYASSIGN = 16;
  public int JJTRELATIONALEXP = 17;
  public int JJTARRAYEXP = 18;
  public int JJTCALLEXP = 19;
  public int JJTADDITIVEEXP = 20;
  public int JJTMULTIPLICATIVEEXP = 21;
  public int JJTLENGTHEXP = 22;
  public int JJTRELATIONALOPERATOR = 23;
  public int JJTADDITIVEOPERATOR = 24;
  public int JJTMULTIPLICATIVEOPERATOR = 25;
  public int JJTINTEGERCONSTNODE = 26;
  public int JJTTRUENODE = 27;
  public int JJTFALSENODE = 28;
  public int JJTTHISNODE = 29;
  public int JJTNEWINTARRAYNODE = 30;
  public int JJTNEWCLASSNODE = 31;
  public int JJTNOTNODE = 32;
  public int JJTIDENTIFIER = 33;
  public int JJTEXPLIST = 34;
  public int JJTEXPREST = 35;


  public String[] jjtNodeName = {
    "Program",
    "MainClass",
    "void",
    "ClassDeclSimple",
    "ClassDeclExtends",
    "VarDecl",
    "MethodDecl",
    "ReturnStm",
    "FormalList",
    "FormalRest",
    "Type",
    "Block",
    "If",
    "While",
    "Print",
    "Assign",
    "ArrayAssign",
    "RelationalExp",
    "ArrayExp",
    "CallExp",
    "AdditiveExp",
    "MultiplicativeExp",
    "LengthExp",
    "RelationalOperator",
    "AdditiveOperator",
    "MultiplicativeOperator",
    "IntegerConstNode",
    "TrueNode",
    "FalseNode",
    "ThisNode",
    "NewIntArrayNode",
    "NewClassNode",
    "NotNode",
    "Identifier",
    "ExpList",
    "ExpRest",
  };
}
/* JavaCC - OriginalChecksum=e40824ae8cf44a37faeb9bead172656f (do not edit this line) */
