/* Generated By:JavaCC: Do not edit this line. MiniJavaParserTreeConstants.java Version 7.0.9 */
package AST;

public interface MiniJavaParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAINCLASS = 1;
  public int JJTVOID = 2;
  public int JJTCLASSDECLSIMPLE = 3;
  public int JJTCLASSDECLEXTENDS = 4;
  public int JJTVARDECL = 5;
  public int JJTMETHODDECL = 6;
  public int JJTFORMALLIST = 7;
  public int JJTFORMALREST = 8;
  public int JJTTYPE = 9;
  public int JJTBLOCK = 10;
  public int JJTIF = 11;
  public int JJTWHILE = 12;
  public int JJTPRINT = 13;
  public int JJTASSIGN = 14;
  public int JJTARRAYASSIGN = 15;
  public int JJTRELATIONALEXP = 16;
  public int JJTARRAYEXP = 17;
  public int JJTCALLEXP = 18;
  public int JJTADDITIVEEXP = 19;
  public int JJTMULTIPLICATIVEEXP = 20;
  public int JJTLENGTHEXP = 21;
  public int JJTRELATIONALOPERATOR = 22;
  public int JJTADDITIVEOPERATOR = 23;
  public int JJTMULTIPLICATIVEOPERATOR = 24;
  public int JJTINTEGERCONSTNODE = 25;
  public int JJTTRUENODE = 26;
  public int JJTFALSENODE = 27;
  public int JJTTHISNODE = 28;
  public int JJTNEWINTARRAYNODE = 29;
  public int JJTNEWCLASSNODE = 30;
  public int JJTNOTNODE = 31;
  public int JJTIDENTIFIER = 32;
  public int JJTEXPLIST = 33;
  public int JJTEXPREST = 34;


  public String[] jjtNodeName = {
    "Program",
    "MainClass",
    "void",
    "ClassDeclSimple",
    "ClassDeclExtends",
    "VarDecl",
    "MethodDecl",
    "FormalList",
    "FormalRest",
    "Type",
    "Block",
    "If",
    "While",
    "Print",
    "Assign",
    "ArrayAssign",
    "RelationalExp",
    "ArrayExp",
    "CallExp",
    "AdditiveExp",
    "MultiplicativeExp",
    "LengthExp",
    "RelationalOperator",
    "AdditiveOperator",
    "MultiplicativeOperator",
    "IntegerConstNode",
    "TrueNode",
    "FalseNode",
    "ThisNode",
    "NewIntArrayNode",
    "NewClassNode",
    "NotNode",
    "Identifier",
    "ExpList",
    "ExpRest",
  };
}
/* JavaCC - OriginalChecksum=c6ab76316ed278a86d2f73c276812931 (do not edit this line) */
