/* Generated By:JJTree&JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package AST;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int LBRACE = 2;
  /** RegularExpression Id. */
  int RBRACE = 3;
  /** RegularExpression Id. */
  int PUBLIC = 4;
  /** RegularExpression Id. */
  int STATIC = 5;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int BOOLEAN = 9;
  /** RegularExpression Id. */
  int MAIN = 10;
  /** RegularExpression Id. */
  int EXTENDS = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int LENGTH = 18;
  /** RegularExpression Id. */
  int THIS = 19;
  /** RegularExpression Id. */
  int NEW = 20;
  /** RegularExpression Id. */
  int LPAREN = 21;
  /** RegularExpression Id. */
  int RPAREN = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int STAR = 24;
  /** RegularExpression Id. */
  int FSLASH = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int MINUS = 27;
  /** RegularExpression Id. */
  int PRINT = 28;
  /** RegularExpression Id. */
  int LSQUARE = 29;
  /** RegularExpression Id. */
  int RSQUARE = 30;
  /** RegularExpression Id. */
  int GT = 31;
  /** RegularExpression Id. */
  int LT = 32;
  /** RegularExpression Id. */
  int ASSIGN = 33;
  /** RegularExpression Id. */
  int SEMI = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int DOT = 36;
  /** RegularExpression Id. */
  int EXCLAIM = 37;
  /** RegularExpression Id. */
  int IDENTIFIER = 38;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 39;
  /** RegularExpression Id. */
  int LETTER = 40;
  /** RegularExpression Id. */
  int DIGIT = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"{\"",
    "\"}\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"String\"",
    "\"int\"",
    "\"boolean\"",
    "\"main\"",
    "\"extends\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "\"length\"",
    "\"this\"",
    "\"new\"",
    "\"(\"",
    "\")\"",
    "\"&&\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"System.out.println\"",
    "\"[\"",
    "\"]\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"!\"",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "<LETTER>",
    "<DIGIT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 46>",
    "<token of kind 47>",
  };

}
