/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package Lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 1;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 2;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"class\"",
    "\"{\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"(\"",
    "\"String\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"}\"",
    "\"extends\"",
    "\";\"",
    "\"return\"",
    "\",\"",
    "\"int\"",
    "\"boolean\"",
    "\"=\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"System.out.println\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"!\"",
  };

}
